version: '3'
networks:
  net:
services:
  jenkins:
    image: jenkins
    container_name: jenkins
    build:
      context: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ${PWD}/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/Jenkinsfile:/var/jenkins_home/Jenkinsfile
    networks:
      - net
    environment:
      - TZ=Asia/Jerusalem
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
        #    restart: always
    #    command: /usr/local/bin/jenkins.sh


    #  remote_host:
    #    container_name: remote-host
    #    image: remote-host
    #    build:
    #      context: centos7
    #    networks:
    #      - net
    #    volumes:
    #      - ${PWD}/my_python_script.py:/app/my_python_script.py
    #    depends_on:
    #      - jenkins
    #    restart: always


